name: Python CI

on:
  push:
    branches:
      - main

jobs:
  python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show files
        run: ls -la

      - name: Run python
        run: python3 app.py
