name: First CI

on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print message
        run: echo "Hello from GitHub Action"

      - name: Who am I
        run: whoami

      - name: Show current directory
        run: pwd

      - name: Show hostname
        run: hostname

      - name: Show files
        run: ls -la

      - name: Show Docker version
        run: docker --version

      - name: Show Python version
        run: python3 --version

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show files
        run: ls -la
